# Generated by Django 2.1.1 on 2019-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('status', models.CharField(blank=True, choices=[('COM', 'Complete'), ('DEL', 'Deleted'), ('NEW', 'New'), ('FUT', 'Future'), ('CAN', 'Canceled'), ('INP', 'In Progress')], default='NEW', max_length=4)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('prereq_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('HOU', 'Housework'), ('PUR', 'Purchase List'), ('JLL', 'Work (JLL)'), ('FAM', 'Family'), ('HEA', 'Health'), ('LEA', 'Learning'), ('GDK', 'Gadake'), ('TF', 'Thirsty Flirt'), ('TODO', 'ToDo List App')], max_length=4, null=True)),
                ('create_ts', models.DateTimeField(auto_now=True)),
                ('complete_ts', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.CharField(blank=True, choices=[('KEI', 'Keith'), ('JES', 'Jess')], default='KEI', max_length=4, null=True)),
                ('occurence', models.CharField(blank=True, choices=[('ONCE', 'One Time'), ('DAI', 'Daily'), ('WEE', 'Weekly'), ('MON', 'Monthy'), ('YEA', 'Yearly')], default='ONCE', max_length=4, null=True)),
                ('occurence_desc', models.CharField(blank=True, max_length=16, null=True)),
                ('priority', models.CharField(blank=True, choices=[('URG', 'Urgent'), ('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=4, null=True)),
                ('percent_complete', models.FloatField(blank=True, null=True)),
                ('time_estimate_val', models.FloatField(blank=True, null=True)),
                ('time_estimate_metric', models.CharField(blank=True, choices=[('MIN', 'Minute'), ('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MON', 'Month'), ('YEAR', 'Year')], max_length=4, null=True)),
                ('time_actual_val', models.FloatField(blank=True, null=True)),
                ('time_actual_metric', models.CharField(blank=True, choices=[('MIN', 'Minute'), ('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MON', 'Month'), ('YEAR', 'Year')], max_length=4, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('orig_text', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
    ]
