# Generated by Django 2.1.2 on 2019-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, choices=[('KEI', 'Keith'), ('JES', 'Jess'), ('GRR', 'Nonno'), ('JMR', 'Nonna'), ('TMW', 'PAPA'), ('SWW', 'Grandma')], default='KEI', max_length=4, null=True),
        ),
    ]
