# Generated by Django 2.1.2 on 2019-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190507_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
