# Generated by Django 2.2.2 on 2019-06-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190612_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, choices=[('ME', 'Me'), ('SPO', 'Spouse'), ('KID', 'Kid')], default='KEI', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('HOU', 'Housework'), ('PUR', 'Purchase List'), ('WOR', 'Work'), ('FAM', 'Family'), ('HEA', 'Health'), ('LEA', 'Learning'), ('TODO', 'ToDo List App')], max_length=4, null=True),
        ),
    ]
